### ISSUE TITLE
this extention unsupport IValidatableObject?

### ISSUE THREAD

**Issue by uliian** [xt0rted/Nancy.Validation.DataAnnotations.Extensions#23]
this extention unsupport IValidatableObject?
I define a class , imp IValidatableObject,it can't valid,yield return a ValidationResult.
but ModelValidationResult.IsValid is true

**Comment by xt0rted** [comment]
`IValidatableObject` is handled by [Nancy.Validation.DataAnnotations](https://github.com/NancyFx/Nancy/tree/master/src/Nancy.Validation.DataAnnotations) which this project depends on. The code to handle that is in [DefaultValidatableObjectAdapter.cs](https://github.com/NancyFx/Nancy/blob/2cf0a22ea83c13c3e10fa8ef784810c3dc05f079/src/Nancy.Validation.DataAnnotations/DefaultValidatableObjectAdapter.cs) and you can also define your own implementation if needed. There's also a demo of `IValidatableObject` in one of the Nancy samples at [Nancy.Demo.Validation](https://github.com/NancyFx/Nancy/blob/45860c82e4df8e2d380997ddf1d19d61400fb145/src/Nancy.Demo.Validation/Models/Customer.cs#L7)
